### ISSUE TITLE
Update nuget package image

### ISSUE THREAD

**Issue by shweaver-MSFT** [CommunityToolkit/Graph-Controls#144]
## Describe the bug

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

There is no image shown when attempting to download the various nuget packages.

## Expected behavior

The standard toolkit nuget image should be displayed, just like in the other WCT packages.

## Screenshots

![image](https://user-images.githubusercontent.com/25832310/128908444-201bcb87-d13f-44aa-b911-3ea28451dfa8.png)

## Environment

```
NuGet Package(s): All of them

Package Version(s): 7.1.0-preview1
```

## Additional context
Issue first identified here: https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4100

**Comment by michael-hawker** [comment]
Pointers to where this is done in the main repo:

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/main/build/Windows.Toolkit.Common.props#L13-L14

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/main/build/Windows.Toolkit.Common.targets#L15-L18

**Comment by shweaver-MSFT** [comment]
@michael-hawker, the `Directory.Build.props` and `Directory.Build.targets` are pretty different than what I see in WCT. Do you think it's worth the effort to update the .props and .targets files to be more similar to how WCT does it? Or perhaps if it aint broke, don't fix it?

**Comment by michael-hawker** [comment]
@shweaver-MSFT up to you. We recently restructured the props files in the Toolkit to pull out all the NuGet descriptive ones (you'll see the new common ones in the build directory).

If you want to tinker with it go-ahead, the main toolkit build has a bunch of extra stuff for VS designer stuff (which at some point we may want to copy over here anyway, though maybe after a source generator version works?).

Otherwise, just fixing the image is sufficient. It's always one of those things that's usually not super-important but still always worth the effort of doing. 😋
