### ISSUE TITLE
Unhandled exception in PeoplePicker sample

### ISSUE THREAD

**Issue by shweaver-MSFT** [CommunityToolkit/Graph-Controls#149]
## Describe the bug

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce
1. Launch the SampleTest app
2. Navigate to the PeoplePicker sample
3. See error

## Expected behavior
No exception should occur.

## Screenshots

![image](https://user-images.githubusercontent.com/25832310/131538614-df534416-df71-49ae-8624-fcc16279ee92.png)

**Comment by shweaver-MSFT** [comment]
After some investigation, I've determined that this exception is being caused by the PeoplePickerSample:

```
<ItemsControl Margin="8,0,0,0" ItemsSource="{x:Bind PeopleChooser.ItemsSource}">
    <ItemsControl.ItemTemplate>
        <DataTemplate x:DataType="graph:Person">
            <TextBlock Text="{x:Bind DisplayName}" />
        </DataTemplate>
    </ItemsControl.ItemTemplate>
</ItemsControl>
```

The problem is that the underlying TokenizingTextBox (TTB) is initializing its ItemSource with a default input item (AKA PretokenStringContainer). So on load, the ItemsSource has one non-token item. This is causing the exception, because the DataTemplate is expecting a DataType of `graph:Person`.

That said, I believe that there is still a bug in the underlying TokenizingTextBox because I would expect the `ItemsSource` property to exclude any non-token items. Retrieving ALL items should be done through the `Items` property.

Fixing the bug in TokenizingTextBox should resolve this issue as well.

**Comment by michael-hawker** [comment]
Thanks for the chat @shweaver-MSFT, I'm taking a look on my dev stream and will see what's going on and write some tests. 🙂

**Comment by michael-hawker** [comment]
@shweaver-MSFT have you seen this issue before?

![image](https://user-images.githubusercontent.com/24302614/133340410-0cd728d1-4dd2-4878-8b79-1d59c7cc132a.png)

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The requested operation requires an element of type 'Object', but the target element has type 'Array'.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
>	[Async] CommunityToolkit.Graph.dll!CommunityToolkit.Graph.Extensions.GraphExtensions.FindUserAsync(Microsoft.Graph.GraphServiceClient graph, string query) Line 59	C#
```

**Comment by michael-hawker** [comment]
Ah, nevermind, I didn't have "Enable Just My Code on" it's some internal graph exception which maybe is expected? As it works now:

![image](https://user-images.githubusercontent.com/24302614/133340800-4bf27d4e-2286-45d9-b126-3fa608997286.png)

I'll submit a PR to this repo for now and then continue to investigate the issue in the TokenizingTextBox. It's definitely [related to us overwriting the ItemsSource here](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/03c3f3c262ea395e66098b8de7945f3651a6bf37/Microsoft.Toolkit.Uwp.UI.Controls.Input/TokenizingTextBox/TokenizingTextBox.cs#L94). We should leave the original collection as the bound ItemsSource. We just didn't catch this before.

So, in this case since we bind to the control's ItemsSource (instead of an external one), we're getting the wrapped Interspersed collection variant which then doesn't behave as we expect.

**Comment by michael-hawker** [comment]
Was able to reproduce this in the main Sample App as well (though not to a crashing extent, but a visible one): https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4248

It's always been there 🙁, but mostly invisible. Which is how we missed it.

I think I have a straight-forward solution??? Going to write some unit tests and go from there first though to ensure we have a proper fix.
